#
# File was generated using command
# brew list
#

brew 'abseil'
brew 'awscli'
brew 'gcc'
brew 'iperf'
brew 'libuv'
brew 'msgpack'
brew 'pkg-config'
brew 'ripgrep'
brew 'xz'
brew 'gdbm'
brew 'isl'
brew 'libyaml'
#brew 'node'
brew 'postgresql'
brew 'ruby-build'
brew 'z3'
brew 'autoconf'
brew 'gettext'
brew 'jq'
brew 'lz4'
brew 'numpy'
brew 'postgresql@14'
brew 'six'
brew 'zstd'
brew 'aws-sdk-cpp'
brew 'gflags'
brew 'krb5'
brew 'm4'
brew 'oniguruma'
brew 'protobuf'
brew 'openjdk'
brew 'cmake'
brew 'opensearch'
brew 'colima'
brew 'redis'
brew 'snappy'
brew 'brotli'
brew 'glog'
brew 'libidn2'
brew 'mariadb'
brew 'openblas'
brew 'python@3.9'
brew 'sqlite'
brew 'bzip2'
brew 'gmp'
brew 'libmpc'
brew 'mecab'
brew 'openssl@1.1'
brew 'rapidjson'
brew 'the_silver_searcher'
brew 'c-ares'
brew 'groonga'
brew 'libnghttp2'
brew 'mecab-ipadic'
brew 'openssl@3'
brew 'rbenv'
brew 'thrift'
brew 'ca-certificates'
brew 'grpc'
brew 'libpq'
brew 'mpdecimal'
brew 'pcre'
brew 're2'
brew 'utf8proc'
brew 'fzf'
brew 'icu4c'
brew 'libunistring'
brew 'mpfr'
brew 'pcre2'
brew 'readline'
brew 'wget'
brew 'gh'
brew 'solargraph'
brew 'duckdb'
brew 'pyenv'

# cask 'slack'
# cask 'iterm2'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'bruno'
# cask 'raycast'
cask 'miniconda'
