# Un comment this line and this in last one to double check
# why zsh is loading so slow
# zmodload zsh/zprof

export EDITOR='vim'

###################
# history searching setup
###################
HISTFILE=$HOME/.zsh_history
SAVEHIST=50000
HISTSIZE=50000

setopt INC_APPEND_HISTORY     # Immediately append to history file
setopt EXTENDED_HISTORY       # Record timestamp in history
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history
setopt HIST_IGNORE_DUPS       # Don't record an entry that was just recorded again
setopt HIST_IGNORE_ALL_DUPS   # Delete old recorded entry if new entry is a duplicate
setopt HIST_FIND_NO_DUPS      # Do not display a line previously found
setopt HIST_IGNORE_SPACE      # Don't record an entry starting with a space:
setopt HIST_SAVE_NO_DUPS      # Don't write duplicate entries in the history file:
setopt SHARE_HISTORY          # Share history between all sessions:
unsetopt HIST_VERIFY          # Execute commands using history (e.g.: using !$) immediately:

#############
# Completion
#############

# Add completions installed through Homebrew packages
# See: https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
  FPATH=/usr/local/share/zsh/site-functions:$FPATH
fi

autoload -Uz compinit && compinit

unsetopt flowcontrol
setopt auto_menu
setopt complete_in_word
setopt always_to_end
setopt auto_pushd

# don't expand aliases _before_ completion has finished
#   like: git comm-[tab]
setopt complete_aliases

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# git plugin
source $HOME/zsh.d/git.plugin.zsh

# prompt customization
autoload -Uz vcs_info
precmd() { vcs_info }
autoload colors && colors

zstyle ':vcs_info:git:*' formats '(%b) '

setopt PROMPT_SUBST

PROMPT="%(?:%{$fg_bold[green]%}%1{➜%} :%{$fg_bold[red]%}%1{➜%} ) %{$fg[cyan]%}%c%{$reset_color%}"
PROMPT+=' $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}%1{✗%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"

# ruby setup
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - --no-rehash)" # after installing ruby run: rbenv rehash

# aliases
source $HOME/.aliases

# private aliases
source $HOME/.private_aliases

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

# Add default node to path (for speedup)"
export PATH=~/.nvm/versions/node/v15.4.0/bin:$PATH

# node version manager
export NVM_DIR="$HOME/.nvm"
# option --no-use loads node much faster (remove if not needed)
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm

# golang version manager
source $HOME/.gvm/scripts/gvm

# groovy home setup (works on mac os)
export GROOVY_HOME=/usr/local/opt/groovy/libexec

[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# Below removed brew --prefix openssl@1.1 because it's taking 10ms to load
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/opt/homebrew/opt/openssl@1.1"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"

bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[[5D' beginning-of-line
bindkey '^[[5C' end-of-line
bindkey '^[[3~' delete-char
bindkey '^?' backward-delete-char

export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# fzf
# fzf via Homebrew
if [ -e /opt/homebrew/opt/fzf/shell/completion.zsh ]; then
  source /opt/homebrew/opt/fzf/shell/key-bindings.zsh
  source /opt/homebrew/opt/fzf/shell/completion.zsh
else
  # fzf via local installation
  if [ -e ~/.fzf ]; then
    source ~/.fzf/shell/key-bindings.zsh
    source ~/.fzf/shell/completion.zsh
    if [[ ! "$PATH" == *$HOME.fzf/bin* ]]; then
      export PATH="$PATH:$HOME/.fzf/bin"
    fi
  fi
fi

if type fzf &> /dev/null && type rg &> /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*" --glob "!vendor/*"'
  export FZF_CTRL_T_COMMAND='rg --files --hidden --follow --glob "!.git/*" --glob "!vendor/*"'
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# Uncomment belows command why zsh is loading so slow
# zprof
# END OF FILE